name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Documentation
        run: |
          doxygen Doxyfile

      - name: Deploy Documentation to GitHub Pages
        run: |
          # Move generated HTML files to the docs/html directory, creating it if necessary
          mkdir -p docs/html
          mv html/* docs/html/

          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Add the generated documentation
          git add docs/html

          # Commit the changes only if there are changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update documentation"
            git push origin main
          else
            echo "No changes to commit"
          fi
