name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Documentation
        run: doxygen Doxyfile

      # Add a debug step to check contents of docs/md
      - name: Debug markdown generation
        run: |
          echo "Checking the contents of the docs/md directory"
          ls -l docs/md

      - name: Update README.md with Documentation
        run: |
          # Clear existing content in README.md and write new header
          echo "# API Documentation" > README.md

          # Check if there are any markdown files and append to README.md
          for file in docs/md/*.md; do
            if [ -f "$file" ]; then
              cat "$file" >> README.md
            else
              echo "No markdown files found in docs/md"
            fi
          done

      - name: Cleanup generated Markdown files
        run: |
          # Remove the generated Markdown files and directories
          rm -rf docs/md

      - name: Commit and Push updated README.md
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Add and commit the README.md file
          git add README.md

          # Commit the changes only if there are changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated documentation update"
            git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit"
          fi
